### ISSUE TITLE
[ППУ] [Необходимо сейчас] Ники администраторов

### ISSUE THREAD

**Issue by LenochkaTihonova** [questionableprofile/eswres#1]
При отправке сообщения, в конце ника администратора в скобках серым цветом будет писаться слово mod

**Comment by questionableprofile** [comment]
Это действительно необходимо?

**Comment by LenochkaTihonova** [comment]
> Это действительно необходимо?

Для того, чтобы не было игроков, выдающих себя за администраторов.

**Comment by questionableprofile** [comment]
Я думаю это не проблема, что кто-то выдаёт себя за администраторов. Важная информация в любом случае распространяется в группе.

**Comment by LenochkaTihonova** [comment]
> Я думаю это не проблема, что кто-то выдаёт себя за администраторов. Важная информация в любом случае распространяется в группе.

И всё-таки мне кажется, что стоит такое реализовать. Вдруг найдутся те, которые будут всерьёз верить сообщениям какого-то самозванца-админа из чатика.

**Comment by questionableprofile** [comment]
Это хорошо. Если спамеров в чатике внезапно будут отправлять в мут такие "замозванцы", то опасаться известные личности будут и настоящих самозванцев. 
К тому же это ишью исключительно к серверсайд.

**Comment by LenochkaTihonova** [comment]
Действительно.
