### ISSUE TITLE
[БАГИ] Перезаход в игру

### ISSUE THREAD

**Issue by LenochkaTihonova** [questionableprofile/eswres#18]
При перезаходе в игру ты оказываешься на начальном, вроде бы, этапе локации.
Допустим, я в катакомбах старого корпуса. Перезахожу в игру, и вот я уже возле входа в старый корпус.

**Comment by questionableprofile** [comment]
Уже пофиксил, скоро отправлю.

**Comment by questionableprofile** [comment]
Готово.
